### ISSUE TITLE
bucket exists check is failing

### ISSUE THREAD

**Issue by mcuervoe** [FieryCod/holy-lambda#56] opened 2021-06-05 18:57 UTC
I am able to create the bucket successfully with bb bucket:create

```
[holy-lambda] Command <bucket:create>
[holy-lambda] Creating a bucket normon-monitor-96661897a56449f1954de8a4627c
[holy-lambda] Bucket normon-monitor-96661897a56449f1954de8a4627c has been succesfully created!
```

If I go to the AWS console, I see the bucket created

,However whenever I try to pack or deploy, the command fails because it said that the bucket does not exists and it is  not able to create it 

```
$ bb stack:pack
[holy-lambda] Command <stack:pack>
[holy-lambda] Bucket normon-monitor-96661897a56449f1954de8a4627c does not exists. Creating one!
[holy-lambda] Command <bucket:create>
[holy-lambda] Creating a bucket normon-monitor-96661897a56449f1954de8a4627c
[holy-lambda] Unable to create a bucket normon-monitor-96661897a56449f1954de8a4627c.
[holy-lambda] AWS command output:
------------------------------------------
make_bucket failed: s3://normon-monitor-96661897a56449f1954de8a4627c5555 An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it.
------------------------------------------
```

This is the output of bb stack:doctor

````
[holy-lambda] Command <stack:doctor>
[holy-lambda] ---------------------------------------
[holy-lambda]  Checking health of holy-lambda stack
[holy-lambda]  Home directory is:        /home/miguel
[holy-lambda]  Project directory is:     /home/miguel/git/onetech/normon-monitor
[holy-lambda]  AWS SAM version:          SAM CLI, version 1.23.0
[holy-lambda]  AWS CLI version:          aws-cli/2.0.42 Python/3.7.3 Linux/4.19.128-microsoft-standard exe/x86_64.ubuntu.18
[holy-lambda]  AWS directory is:         /home/miguel/.aws
[holy-lambda]  AWS directory exists?:    true
[holy-lambda]  Docker version:           Docker version 20.10.6, build 370c289
[holy-lambda]  Babashka tasks sha:       75831dc72f0ddee55a151bc8e7442b67214607fc
[holy-lambda]  Babashka tasks version:   0.1.49
[holy-lambda]  Babashka version:         babashka v0.4.4
[holy-lambda]  Runtime:                  :babashka
[holy-lambda]  Runtime entrypoint:       com.nubizzi.normon-monitor.core
[holy-lambda]  Stack name:               normon-monitor-96661897a56449f1954de8a4627c40d1-stack
[holy-lambda]  S3 Bucket name:           normon-monitor-96661897a56449f1954de8a4627c
[holy-lambda]  S3 Bucket prefix:         holy-lambda
[holy-lambda]  S3 Bucket exists?:        false
[holy-lambda] ---------------------------------------

[holy-lambda] :runtime looks good
[holy-lambda] :runtime:entrypoint looks good
[holy-lambda] :stack:capabilities looks good
[holy-lambda] :runtime:bootstrap-file is supported only for :native runtime
[holy-lambda] :runtime:native-deps is supported only for :native runtime
[holy-lambda] :runtime:native-image-args are supported only for :native runtime
[holy-lambda] :stack:name looks good
[holy-lambda] property :mvn/local-repo in file deps.edn is correct
[holy-lambda] property :mvn/local-repo in file bb.edn is correct
[holy-lambda] Syncing stack is not required
[holy-lambda] :infra:region definition looks good
[holy-lambda] :infra:bucket-prefix looks good
[holy-lambda] :stack:template looks good
[holy-lambda] :infra:bucket-name looks good, but normon-monitor-96661897a56449f1954de8a4627c does not exists (use bb :bucket:create)
[holy-lambda] Required commands ["aws" "sam" "bb" "docker" "clojure" "zip" "id" "clj-kondo" "bash"] installed!

[holy-lambda] Validating template.yml
2021-06-05 20:42:07 Loading policies from IAM...
2021-06-05 20:42:09 Finished loading policies from IAM.
/home/miguel/git/onetech/normon-monitor/template.yml is a valid SAM Template

````

I think the significant line is

[holy-lambda]  S3 Bucket exists?:        false

**Comment by FieryCod** [comment] 2021-06-05 20:06
@mcuervoe Could you please run the following command and tell me what do you see?

```
aws s3 ls
```

**Comment by FieryCod** [comment] 2021-06-05 21:51
@mcuervoe I have carefully studied your report and some parts of the report do not match. 
- stack sha is different than bucket sha
- normon-monitor-96661897a56449f1954de8a4627c is not the same as s3://normon-monitor-96661897a56449f1954de8a4627c5555, which bucket do you see created on AWS UI?

1. Did you modify the report by hand?
2. What is the output of `aws s3 ls`

I don't know in which order have you executed the commands. If you could share your `bb.edn` and the steps to reproduce the issue that would be helpful.

**Comment by mcuervoe** [comment] 2021-06-06 12:11
Hi,

Thanks for your quick response. I see now where it was the problem: in the terminal where I was launching bb, I had a different AWS_PROFILE to the one defined in bb.edn. I thought bb was using the profile in the configuration file.

Now, with the same profile in the environment variable, it works.

Again, thank you very much. This project promise to be what I was looking for for a long time.

**Comment by FieryCod** [comment] 2021-06-06 16:53
@mcuervoe it should use profile defined in `bb.edn, although setting AWS_PROFILE might override it since Holy Lambda uses `aws` command under the hood. I will try to patch it somehow :) 


Thank you for your kind words! If you find yourself in trouble then you can always jump to our #holy-lambda channel on Slack.

**Comment by FieryCod** [comment] 2021-06-06 17:12
@mcuervoe Could you please check the newest sha version for tasks: `999742a3bd422fe53f82b3c657f7b56b5d4782e6`.
In this commit, I have added `--profile` and `--region` options for the s3 list command which is used for checking if the bucket is already created. If it doesn't help, then probably AWS_PROFILE overwrites profile set via the command. 

Please give it a spin!

**Comment by mcuervoe** [comment] 2021-06-07 21:43
Hi,

I tested the new version, removing the AWS_PROFILE in the environment and with an AWS_PROFILE different from the AWS_PROFILE in the bb.edn. In both cases, it works fine.

Thanks very much

FYI: I already have three lambdas in production created with Holy Lambda!

**Comment by FieryCod** [comment] 2021-06-08 08:22
@mcuervoe I'm very happy to hear this! In case of any troubles with holy-lambda, please let me know! Thank you for reaching out with this issue! 

PS: Is it a hobby project or a commercial one? If it's a commercial one then may I put the name of the company in the README?

**Comment by mcuervoe** [comment] 2021-06-08 09:14
Hi @FieryCod, 

It is a commercial project, but I am not allowed to disclose the name of my client. I can tell that it is an important pharmaceutical, and we are using the lambda created with holy-lambda to monitor the health of several services.

I can also share the performance that I get using native and babashka: 

Cold Execution Time Babashka: 550ms
Cold Execution Time Native:  550ms

Warm Execution Time Babashka: 15ms
Warm Execution Time Native:  15ms

Memory Babashka: 150MB
Memory Native: 71MB

So as you can see, I do not see an improvement in speed using the native runtime, but it makes sense since my process is I/O bound.

However, there is a significant memory used improvement.

Hope this helps

**Comment by FieryCod** [comment] 2021-06-09 10:36
Hi @mcuervoe! Thank you very much for your detailed response. I'm very happy with the results, although I'm a little surprised that the `babashka` runtime is as fast as native one in your case. 

Thanks for testing out the fix! Closing the issue!

**Closed by FieryCod** 2021-06-09 10:36 UTC
Labels: bb:tasks, bug
